-- @requires column guest_rsvps.retired_at
--
-- 097: when a guest answer left the plan because its person joined it as a
-- member, told apart from a moderator taking it down.
--
-- ASCII only, like 065 and 082: the embedded server the boot-safety suite runs
-- is WIN1252.
--
-- ---------------------------------------------------------------------------
-- WHAT WENT WRONG
--
-- Two doors retire a guest row when its person becomes a member: the share
-- link's join and the invite accepted in the app (utils/guestRsvp.js,
-- RETIRE_ON_LINK_JOIN_SQL and RETIRE_ON_INVITE_ACCEPT_SQL). They hide the row,
-- so it leaves every count, and hiding was all they wrote. A moderator's
-- takedown is also nothing but a hidden row, and the takedown's replay guard
-- (routes/guest.js nameIsTakenDown) refuses any name a hidden row on the plan
-- carries. So Sam answered the link as "Sam", made the account "Sam Rivera"
-- and joined, and from then on:
--
--   - a different Sam opening the same link was told "That name cannot be used
--     on this flock", the sentence a takedown gets;
--   - the first Sam's own browser was told their answer was gone and to answer
--     again, on a plan they had just joined, and answering as Sam was refused
--     the same way.
--
-- ---------------------------------------------------------------------------
-- THE COLUMN
--
-- retired_at is set by the two retire statements, in the same UPDATE that
-- hides the row, and by nothing else. A hidden row with it NULL is a takedown;
-- a hidden row with it set was retired on a join. The moderator's hide and
-- un-hide of a guest row clear it (routes/admin.js TAKEDOWN_TARGETS), so a
-- retired row a moderator then takes down is a takedown like any other, and a
-- row brought back is a live answer again.
--
-- Nullable with no default, so every row that exists reads as it did before:
-- a row hidden before this file cannot be told apart after the fact, and
-- treating it as a takedown is the side that keeps a moderator's decision.
--
-- ---------------------------------------------------------------------------
-- REPLAY
--
-- IF NOT EXISTS, and nothing is backfilled, so a second pass changes nothing.

ALTER TABLE guest_rsvps ADD COLUMN IF NOT EXISTS retired_at TIMESTAMPTZ;
